export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_API_SAMP_SERVER = 'GET_API_SAMP_SERVER';

export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

export const USER_LOADED = 'USER_LOADED';

export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const CHANGE_EMAIL_FAIL = 'CHANGE_EMAIL_FAIL';
export const CHANGE_EMAIL_SUCCESS = 'CHANGE_EMAIL_SUCCESS';

export const GET_USER_CHARACTERS = 'GET_USER_CHARACTERS';
export const GET_CHARACTERS = 'GET_CHARACTERS';

export const AUTH_ERROR = 'AUTH_ERROR';
export const API_SAMP_SERVER_ERROR = 'API_SAMP_SERVER_ERROR';

export const LOGOUT = 'LOGOUT';
