export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_API_SAMP_SERVER = 'GET_API_SAMP_SERVER';

export const COUNT_SERVER_USERS = 'COUNT_SERVER_USERS';
export const COUNT_SERVER_USERS_FAIL = 'COUNT_SERVER_USERS_FAIL';
export const COUNT_SERVER_VEHICLES = 'COUNT_SERVER_VEHICLES';
export const COUNT_SERVER_VEHICLES_FAIL = 'COUNT_SERVER_VEHICLES_FAIL';
export const COUNT_SERVER_PROPERTIES = 'COUNT_SERVER_PROPERTIES';
export const COUNT_SERVER_PROPERTIES_FAIL = 'COUNT_SERVER_PROPERTIES_FAIL';
export const COUNT_SERVER_USER_APPS = 'COUNT_SERVER_USER_APPS';
export const COUNT_SERVER_USER_APPS_FAIL = 'COUNT_SERVER_USER_APPS_FAIL';

export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const EMAIL_VERIFICATION_SENT = 'EMAIL_VERIFICATION_SENT';
export const EMAIL_VERIFICATION_FAIL = 'EMAIL_VERIFICATION_FAIL';
export const CONFIRM_EMAIL_VERIFICATION = 'CONFIRM_EMAIL_VERIFICATION';
export const CONFIRM_EMAIL_VERIFICATION_FAIL = 'CONFIRM_EMAIL_VERIFICATION_FAIL';

export const LOAD_QUIZ = 'LOAD_QUIZ';
export const LOAD_QUIZ_SCENARIO = 'LOAD_QUIZ_SCENARIO';
export const LOAD_QUIZ_SCENARIO_FAIL = 'LOAD_QUIZ_SCENARIO_FAIL';
export const QUIZ_UPDATE = 'QUIZ_UPDATE';
export const QUIZ_GRADE = 'QUIZ_GRADE';
export const QUIZ_SUBMISSIONS = 'QUIZ_SUBMISSIONS';
export const REQUEST_QUIZ_RESULT = 'REQUEST_QUIZ_RESULT';
export const QUIZ_RESULT = 'QUIZ_RESULT';
export const QUIZ_RESULT_FAIL = 'QUIZ_RESULT_FAIL';
export const PUSH_QUIZ_SCORE = 'PUSH_QUIZ_SCORE';
export const CLEAR_QUIZ = 'CLEAR_QUIZ';

export const GET_USER_CHARACTERS = 'GET_USER_CHARACTERS';
export const GET_USER_CHARACTERS_FAIL = 'GET_USER_CHARACTERS_FAIL';
export const GET_CHARACTER_DETAIL = 'GET_CHARACTER_DETAIL';
export const GET_CHARACTER_DETAIL_FAIL = 'GET_CHARACTER_DETAIL_FAIL';
export const GET_CHARACTER_FACTION_MEMBERS = 'GET_CHARACTER_FACTION_MEMBERS';
export const GET_CHARACTER_FACTION_MEMBERS_FAIL = 'GET_CHARACTER_FACTION_MEMBERS_FAIL';
export const REQUEST_CREATE_CHARACTER = 'REQUEST_CREATE_CHARACTER';
export const CHARACTER_CREATED = 'CHARACTER_CREATED';
export const CHARACTER_CREATED_FAIL = 'CHARACTER_CREATED_FAIL';
export const CHARACTER_DELETED = 'CHARACTER_DELETED';
export const CHARACTER_DELETED_FAIL = 'CHARACTER_DELETED_FAIL';

export const GET_CHARACTER_ADMIN_WARNS = 'GET_CHARACTER_ADMIN_WARNS';
export const GET_CHARACTER_ADMIN_WARNS_FAIL = 'GET_CHARACTER_ADMIN_WARNS_FAIL';
export const GET_CHARACTER_INVENTORY = 'GET_CHARACTER_INVENTORY';
export const GET_CHARACTER_INVENTORY_FAIL = 'GET_CHARACTER_INVENTORY_FAIL';
export const GET_CHARACTER_VEHICLES = 'GET_CHARACTER_VEHICLES';
export const GET_CHARACTER_VEHICLES_FAIL = 'GET_CHARACTER_VEHICLES_FAIL';
export const GET_CHARACTER_PROPERTY = 'GET_CHARACTER_PROPERTY';
export const GET_CHARACTER_PROPERTY_FAIL = 'GET_CHARACTER_PROPERTY_FAIL';
export const GET_CHARACTER_BIZZ = 'GET_CHARACTER_BIZZ';
export const GET_CHARACTER_BIZZ_FAIL = 'GET_CHARACTER_BIZZ_FAIL';

export const GET_HEADLINE_NEWS = 'GET_HEADLINE_NEWS';
export const GET_HEADLINE_NEWS_FAIL = 'GET_HEADLINE_NEWS_FAIL';
export const GET_NEWS = 'GET_NEWS';
export const GET_NEWS_FAIL = 'GET_NEWS_FAIL';
export const GET_FACTION_NEWS = 'GET_FACTION_NEWS';
export const GET_FACTION_NEWS_FAIL = 'GET_FACTION_NEWS_FAIL';
export const GET_NEWS_DETAIL = 'GET_NEWS_DETAIL';
export const GET_NEWS_DETAIL_FAIL = 'GET_NEWS_DETAIL_FAIL';

export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_SENT = 'FORGOT_PASSWORD_SENT';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';

export const RESET_NEW_PASSWORD_FAIL = 'RESET_NEW_PASSWORD_FAIL';
export const RESET_NEW_PASSWORD = 'RESET_NEW_PASSWORD';

export const USER_LOADED = 'USER_LOADED';

export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';

export const CHANGE_EMAIL_FAIL = 'CHANGE_EMAIL_FAIL';
export const CHANGE_EMAIL_SUCCESS = 'CHANGE_EMAIL_SUCCESS';
export const CHANGE_EMAIL_REQUEST = 'CHANGE_EMAIL_REQUEST';

export const AUTH_ERROR = 'AUTH_ERROR';
export const GET_API_SAMP_SERVER_ERROR = 'GET_API_SAMP_SERVER_ERROR';

export const LOGOUT = 'LOGOUT';
