export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_API_SAMP_SERVER = 'GET_API_SAMP_SERVER';

export const COUNT_SERVER_USERS = 'COUNT_SERVER_USERS';
export const COUNT_SERVER_USERS_FAIL = 'COUNT_SERVER_USERS_FAIL';

export const COUNT_SERVER_VEHICLES = 'COUNT_SERVER_VEHICLES';
export const COUNT_SERVER_VEHICLES_FAIL = 'COUNT_SERVER_VEHICLES_FAIL';

export const COUNT_SERVER_PROPERTIES = 'COUNT_SERVER_PROPERTIES';
export const COUNT_SERVER_PROPERTIES_FAIL = 'COUNT_SERVER_PROPERTIES_FAIL';

export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOAD_QUIZ = 'LOAD_QUIZ';
export const LOAD_QUIZ_SCENARIO = 'LOAD_QUIZ_SCENARIO';
export const LOAD_QUIZ_SCENARIO_FAIL = 'LOAD_QUIZ_SCENARIO_FAIL';
export const QUIZ_UPDATE = 'QUIZ_UPDATE';
export const QUIZ_GRADE = 'QUIZ_GRADE';
export const QUIZ_SUBMISSIONS = 'QUIZ_SUBMISSIONS';
export const QUIZ_RESULT = 'QUIZ_RESULT';
export const QUIZ_RESULT_FAIL = 'QUIZ_RESULT_FAIL';
export const PUSH_QUIZ_SCORE = 'PUSH_QUIZ_SCORE';

export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

export const USER_LOADED = 'USER_LOADED';

export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const CHANGE_EMAIL_FAIL = 'CHANGE_EMAIL_FAIL';
export const CHANGE_EMAIL_SUCCESS = 'CHANGE_EMAIL_SUCCESS';

export const AUTH_ERROR = 'AUTH_ERROR';
export const GET_API_SAMP_SERVER_ERROR = 'GET_API_SAMP_SERVER_ERROR';

export const LOGOUT = 'LOGOUT';
